# Generated by Django 3.2.6 on 2022-05-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='user', max_length=255, null=True, verbose_name='名称'),
        ),
    ]
