# Generated by Django 3.2.6 on 2022-05-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpd', '0002_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='path',
            field=models.CharField(help_text='配置路径', max_length=255, null=True, verbose_name='路径'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='SMPDAdmin', max_length=255, null=True, verbose_name='名称'),
        ),
    ]
