# Generated by Django 3.2.6 on 2022-05-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smpd', '0003_auto_20220518_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='url',
            new_name='rtsp',
        ),
    ]
