# Generated by Django 3.2.6 on 2022-05-23 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('smpd', '0004_rename_url_camera_rtsp'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='ip',
            field=models.CharField(blank=True, default='192.168.1.64:554', max_length=255, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='path',
            field=models.CharField(blank=True, help_text='配置路径', max_length=255, null=True, verbose_name='路径'),
        ),
    ]
