# Generated by Django 3.2.6 on 2022-05-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpd', '0005_auto_20220523_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='port',
            field=models.CharField(blank=True, default='554', max_length=255, null=True, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip',
            field=models.CharField(blank=True, default='192.168.1.64:554', max_length=255, null=True, verbose_name='IP'),
        ),
    ]
